# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1516ea7d4a0c3bd02e5d763c7ba16d895cf54c7523e2f8d4826b588abe7fd466b8f203359fd373599eac4715bd6c8e33b6299e7da7fb31586695a2693c0c141

test:
  secret_key_base: 38c7ae8433a7c411056156cd493abab65056b36778a28421d6bb9c71b6bfdde4c332503e827d27c4352460a280073ffbaeabec90e9a485e1935fd3aaa2a7825e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
